### ISSUE TITLE
Contact re QUDT

### ISSUE THREAD

**Issue by nicholascar** [OR13/OR13#1]
Hi Orie, please contact me (email in GitHub profile) regarding https://github.com/qudt/qudt-public-repo/issues/247.

I work with geoscience ontologies and I want to see more stuff in QUDT so we have to maintain less stuff. I'm interested in stuff related to your stuff: mineral properties.

I'm also a QUDT technical board member so able to hound them on things if needed.

**Comment by OR13** [comment]
Sorry for never responding to this, I am moving the issue to a more active repo.
